*/
SELECT CITY, LENGTH(CITY) AS min_length
FROM STATION
WHERE LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION) LIMIT 1;

SELECT CITY, LENGTH(CITY) AS max_length
FROM STATION
WHERE LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION) LIMIT 1;
